// <auto-generated />
using System;
using CatAdoptionMobileApp.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatAdoptionMobileApp.EntityFramework.Migrations
{
    [DbContext(typeof(CatAdoptionDbContext))]
    [Migration("20241230204829_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = 0,
                            Breed = "Siamese",
                            DateOfBirth = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fluffy is a very friendly cat. She loves to play with kids and other cats. She is very active and loves to be around people.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_1280.jpg",
                            IsActive = false,
                            Name = "Fluffy",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = 0,
                            Breed = "Persian",
                            DateOfBirth = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Whiskers is a very calm and quiet cat. He loves to sleep and relax. He is very friendly and loves to be pet",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/01/18/07/38/cat-6946505_1280.jpg",
                            IsActive = false,
                            Name = "Whiskers",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = 0,
                            Breed = "Tabby",
                            DateOfBirth = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mittens is a very playful cat. She loves to run around and play with toys. She is very friendly and loves to be around people.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2021/10/27/19/09/cat-6748193_1280.jpg",
                            IsActive = false,
                            Name = "Mittens",
                            Price = 100.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = 0,
                            Breed = "British Shorthair",
                            DateOfBirth = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Socks is a quiet and dignified cat. She enjoys spending time with her family and has a soft, round face.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/01/18/07/36/cat-6946498_1280.jpg",
                            IsActive = false,
                            Name = "Socks",
                            Price = 110.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = 0,
                            Breed = "Bengal",
                            DateOfBirth = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bella is an energetic and curious cat. She loves to explore and is very intelligent, often figuring out how to open doors.",
                            Gender = 1,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/06/20/16/54/cat-7274205_1280.jpg",
                            IsActive = false,
                            Name = "Bella",
                            Price = 140.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = 0,
                            Breed = "Orange Tabby",
                            DateOfBirth = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ginger is a sweet, calm cat who loves to be pampered. She enjoys napping in the sun and curling up on soft blankets.",
                            Gender = 1,
                            ImageUrl = "https://cdn.pixabay.com/photo/2023/09/21/17/05/european-shorthair-8267220_1280.jpg",
                            IsActive = false,
                            Name = "Ginger",
                            Price = 95.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = 0,
                            Breed = "Russian Blue",
                            DateOfBirth = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smokey is a quiet, reserved cat. He is known for his beautiful silvery coat and enjoys being petted when he’s in the mood.",
                            Gender = 1,
                            ImageUrl = "https://cdn.pixabay.com/photo/2021/12/01/18/17/cat-6838844_1280.jpg",
                            IsActive = false,
                            Name = "Smokey",
                            Price = 125.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = 0,
                            Breed = "Ragdoll",
                            DateOfBirth = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oliver is a gentle giant with a calm and loving nature. He’s very affectionate and loves to be held like a baby.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2023/04/07/07/14/cat-7905702_1280.jpg",
                            IsActive = false,
                            Name = "Oliver",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = 0,
                            Breed = "Abyssinian",
                            DateOfBirth = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a playful and active cat. She loves to climb and jump, and she is always full of energy.",
                            Gender = 1,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/11/11/09/26/cat-7584624_1280.jpg",
                            IsActive = false,
                            Name = "Luna",
                            Price = 105.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = 0,
                            Breed = "Sphynx",
                            DateOfBirth = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is an outgoing and social cat. Despite having no fur, he is very warm and enjoys being around people.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/11/16/22/14/cat-1046544_1280.jpg",
                            IsActive = false,
                            Name = "Milo",
                            Price = 95.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = 0,
                            Breed = "Scottish Fold",
                            DateOfBirth = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toby is a calm and loving cat with distinctive folded ears. He enjoys lounging around and being spoiled with treats.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/07/12/27/cat-2603300_1280.jpg",
                            IsActive = false,
                            Name = "Toby",
                            Price = 115.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = 0,
                            Breed = "Birman",
                            DateOfBirth = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chloe is an elegant cat with a luxurious coat. She loves being pampered and enjoys a good scratch behind the ears.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2020/11/22/17/28/cat-5767334_1280.jpg",
                            IsActive = false,
                            Name = "Chloe",
                            Price = 130.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = 0,
                            Breed = "Burmese",
                            DateOfBirth = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Leo is an affectionate and playful cat. He loves attention and follows his owner around the house.",
                            Gender = 0,
                            ImageUrl = "https://cdn.pixabay.com/photo/2022/07/25/15/18/cat-7344042_1280.jpg",
                            IsActive = false,
                            Name = "Leo",
                            Price = 140.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = 0,
                            Breed = "Egyptian Mau",
                            DateOfBirth = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Penny is a lively and graceful cat with a striking spotted coat. She’s very active and loves to play with interactive toys.",
                            Gender = 1,
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/06/08/17/02/cat-4260536_1280.jpg",
                            IsActive = false,
                            Name = "Penny",
                            Price = 120.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.UserFavorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.UserAdoption", b =>
                {
                    b.HasOne("CatAdoptionMobileApp.Domain.Models.Cat", "Cat")
                        .WithMany()
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatAdoptionMobileApp.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CatAdoptionMobileApp.Domain.Models.UserFavorites", b =>
                {
                    b.HasOne("CatAdoptionMobileApp.Domain.Models.Cat", "Cat")
                        .WithMany()
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatAdoptionMobileApp.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
