global using CatAdoptionMobileApp.MAUI.Models;
global using CatAdoptionMobileApp.MAUI.Pages;
global using CatAdoptionMobileApp.MAUI.ViewModels;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.Logging;
global using System.Diagnostics;